[phases.setup]
nixPkgs = [
    "python310",
    "zlib",
    "libffi",
    "openssl",
    "gcc",
    "zbar"  # Correct package name instead of libzbar
]

[phases.install]
commands = [
    "python -m pip install --upgrade pip",
    "pip install wheel",
    "pip install -r requirements.txt"
]

[phases.start]
command = "python app.py"