[phases.setup]
nixPkgs = [
    "python311",
    "zlib",
    "libffi",
    "openssl",
    "gcc",
    "libzbar"  # Required for pyzbar
]

[phases.install]
commands = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.start]
command = "python app.py"